# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  default:
    - step:
        name: Build and Deploy to Production
        deployment: production
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - yarn install
          - yarn build
  branches:
    master:
      - step:
          name: Build and Deploy to Staging
          deployment: staging
          caches:
            - node
          script:
            - yarn install
            - yarn build
            - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"./"
    develop:
      - step:
          name: Build and Deploy to Staging
          deployment: staging
          caches:
            - node
          script:
            - yarn install
            - yarn build
            - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"./"
